{% set name = "pyratlib" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyratlib/pyratlib-0.6.2.tar.gz
  sha256: fb4dfdc6946a3edab24a6325bf1d95a9b353c8fd1639fcf6b0cd2c3c10faac0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python-neo
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - scikit-learn

test:
  imports:
    - pyratlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyratlib/pyrat
  summary: PyRat is a user friendly library in python to analyze data from the DeepLabCut. Developed to help researchers unfamiliar with programming can perform animal behavior analysis more simpler.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyratlib
    - tuliofalmeida
    - abnr
